import json
from pathlib import Path

from everby_agent.schemas.domain import AgentCapabilities, MemoryItem, TodoItem
from everby_agent.schemas.protocol import RpcEvent, RpcRequest, RpcResult

ROOT = Path(__file__).resolve().parents[2]
models = [RpcRequest, RpcEvent, RpcResult, AgentCapabilities, TodoItem, MemoryItem]
schema = {model.__name__: model.model_json_schema(by_alias=True) for model in models}

(ROOT / "src/shared/agent-protocol.schema.json").write_text(
    json.dumps(schema, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
)

generated = """// Generated by agent/scripts/export_schemas.py. Do not edit directly.
export const EVERBY_PROTOCOL_VERSION = 2 as const;
export type AgentEventName =
  | "assistant_delta" | "agent_progress" | "tool_started" | "tool_finished"
  | "assistant_done" | "state_changed" | "notification_requested" | "pet_action" | "error";
export interface AgentRpcError { code: string; message: string; retryable: boolean }
export interface AgentRpcRequest { id: string; protocolVersion: 2; method: string; params: Record<string, unknown> }
export interface AgentRpcEvent { protocolVersion: 2; type: AgentEventName; requestId?: string; data: Record<string, unknown> }
"""
(ROOT / "src/shared/agent-protocol.generated.ts").write_text(generated, encoding="utf-8")
