// Generated by agent/scripts/export_schemas.py. Do not edit directly.
export const SOULDESK_PROTOCOL_VERSION = 2 as const;
export type AgentEventName =
  | "assistant_delta" | "agent_progress" | "tool_started" | "tool_finished"
  | "assistant_done" | "state_changed" | "notification_requested" | "pet_action" | "error";
export interface AgentRpcError { code: string; message: string; retryable: boolean }
export interface AgentRpcRequest { id: string; protocolVersion: 2; method: string; params: Record<string, unknown> }
export interface AgentRpcEvent { protocolVersion: 2; type: AgentEventName; requestId?: string; data: Record<string, unknown> }
